name: Build project and push to dockerhub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project and push docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project with maven
        run: mvn clean install

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dominik4871/todo-list
          context: .
          dockerfile: docker/Dockerfile
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
