name: Build project and push to dockerhub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project and push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project with maven
        run: mvn clean install

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-list:latest
