name: Build project and push to dockerhub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project and push docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate version label
        id: version_label
        run: echo "VERSION_LABEL=version-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build project with maven
        run: mvn clean install

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: dominik4871/todo-list
          tags: ${{ env.VERSION_LABEL }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: todolist
          environment_name: todolist-dev
          version_label: ${{ env.VERSION_LABEL }}
          region: eu-north-1
          deployment_package: devops/dev/docker-compose.yml